import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Your Needs Everyday",
  // description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={`antialiased ${montserrat.className}`}>{children}</body>
    </html>
  );
}
