import "./globals.css";
import { Cabin, Caveat, Tangerine, Play, Noto_Sans_Javanese, Indie_Flower } from "next/font/google";

export const metadata = {
  title: "Your Needs Everyday",
  // description: "Generated by create next app",
};

const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-cabin",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

const tangerine = Tangerine({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-tangerine",
});

const play = Play({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-play",
})

const noto = Noto_Sans_Javanese({
  subsets: ["javanese"],
  variable: "--font-noto",
})

const flower=Indie_Flower({
  subsets: ["latin"],
  variable: "--font-flower",
  weight: "400",
})

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body
        className={`antialiased ${cabin.variable} ${caveat.variable} ${tangerine.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
